add test fixture which exercises wasi sleep
without prior commit, this would crash because wasi is trying
to run in a dummy executor:

[pat@finknottle:viceroy/cli]% cargo test --test sleep
   Compiling viceroy-lib v0.2.2 (/home/pat/src/viceroy/lib)
   Compiling viceroy-cli v0.2.2 (/home/pat/src/viceroy/cli)
    Finished test [unoptimized + debuginfo] target(s) in 16.23s
     Running tests/sleep.rs (/home/pat/src/viceroy/target/debug/deps/sleep-f21a87ee4efbda79)

running 1 test
test empty_ok_response_by_default_after_sleep ... FAILED

failures:

---- empty_ok_response_by_default_after_sleep stdout ----
thread 'tokio-runtime-worker' panicked at 'Cannot wait on pending future: must enable wiggle "async" future and execute on an async Store', /home/pat/.cargo/registry/src/github.com-1ecc6299db9ec823/wiggle-0.28.0/src/lib.rs:946:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'empty_ok_response_by_default_after_sleep' panicked at 'guest worker finished without panicking: JoinError::Panic(...)', lib/src/execute.rs:189:18

failures:
    empty_ok_response_by_default_after_sleep

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.49s